### ISSUE TITLE
Python报错

### ISSUE THREAD

**Issue by Rica123** [chroblert/SecurityBaselineCheck#1]
遇到如下问题，不知道如何解决

![image](https://user-images.githubusercontent.com/29624854/73947221-16ec5180-4932-11ea-84ec-fda4755e2587.png)

**Comment by chroblert** [comment]
1. 后端服务器有没有开启？在这个基线检查脚本的最后有上传检查结果到后端服务器去，如果没有开启，则可以将最后的几行代码注释掉
后端服务器代码位于github.com/chroblert/assetmanage
2. 后端已开启。检查下pamIfSetMinlen的值是什么
