### ISSUE TITLE
执行脚本最后提示 ./linux_baseline_check.sh:行1165: jq: 未找到命令

### ISSUE THREAD

**Issue by yq513** [chroblert/SecurityBaselineCheck#2]
执行脚本最后提示
./linux_baseline_check.sh:行1165: jq: 未找到命令
这个 jq是个什么参数？

**Comment by chroblert** [comment]
这个是json格式化输出的一个命令 需要自己安装一下 可以直接不影响功能的使用，可以直接注释掉-------- 原始邮件 --------发件人： yq513 <notifications@github.com>日期： 2020年2月9日周日 下午3:43收件人： chroblert/SecurityBaselineCheck <SecurityBaselineCheck@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [chroblert/SecurityBaselineCheck] 执行脚本最后提示 ./linux_baseline_check.sh:行1165: jq: 未找到命令 (#2)执行脚本最后提示

./linux_baseline_check.sh:行1165: jq: 未找到命令

这个 jq是个什么参数？
